### ISSUE TITLE
Spotter - RealEstate as Main and DB Design

### ISSUE THREAD

**Issue by Mouris1** [Mouris1/SpotterProps#1]
1. Set Real Estate as the main page;
2. Update icon;
3. Database design based on current json format;
4. Basic api to provide properties information
4.1. list
4.2. details

**Comment by DerekJi2** [comment]
Virtual Host Configuration
--
1. xampp\apache\conf\extra\httpd-vhosts.conf
Add the following lines
NameVirtualHost *
<VirtualHost \*>
    DocumentRoot "I:/Dropbox/Dropbox/xampp/htdocs"
    ServerName localhost
<\/VirtualHost>
<VirtualHost \*>
    ServerName www.myspotter.com
    ServerAlias myspotter.com
    DocumentRoot "I:/Dropbox/Dropbox/xampp/htdocs/spotter"
<\/VirtualHost>
![image](https://user-images.githubusercontent.com/29216624/34153010-70a68be8-e500-11e7-9f2f-4d220f1e92cc.png)

2.  xampp\apache\conf\extra\httpd-ssl.conf
<VirtualHost \_default\_:443> 
    DocumentRoot "I:/Dropbox/Dropbox/xampp/htdocs/spotter" 
    ServerName www.myspotter.com:443 
    ServerAlias myspotter.com:443  
    SSLEngine on 
    SSLCertificateFile "conf/ssl.crt/server.crt" 
    SSLCertificateKeyFile "conf/ssl.key/server.key" 
<\/VirtualHost> 

![image](https://user-images.githubusercontent.com/29216624/34153028-845863aa-e500-11e7-8aa9-9b8c5f61ec67.png)

3. C:\Windows\System32\drivers\etc\hosts
Add one more line at the bottom
127.0.0.1	www.myspotter.com

**Comment by Mouris1** [comment]
I did that what next

**Comment by Mouris1** [comment]
do i have to change I:/Dropbox/Dropbox/xampp/htdocs/spotter to the location on my computer

**Comment by DerekJi2** [comment]
Basic Installations
--
1. Copy frontend/spotter into xampp/htdocs;
2. Update spotter/application/config/database.php, to keep them consistent with your own environment
![image](https://user-images.githubusercontent.com/29216624/34155978-3473e692-e50b-11e7-99f7-090d631df8eb.png)
3. Create Database
Execute the SQL (frontend\spotter\system\database\DB_SpotterProp.sql) to initialise the database

Demo
--
![demo19](https://user-images.githubusercontent.com/29216624/34156458-4cbd150a-e50d-11e7-8e81-ddc2d6ae264a.gif)

**Comment by DerekJi2** [comment]
Answers
--
1. Yes, you have to update the directory like ' I:/Dropbox/Dropbox/xampp/htdocs/spotter' to your own location;
2. Before running the SQL, the database has to be created manually. If another database name is used instead of 'spotterprop', the conf/database.php should be changed accordingly.
3. It's not finished until now. 
4. Still lots of things to do. What I'm going to do next includes:
* Implement real webapi for properties, galleries, etc. (currently only basic apis for types/specifications/features);
* Mocking data in database;
* Implement all the functions in current UI.
-- Dinamically load property types;
-- Implement all search criteria;
-- Combine all search functions 
* Fix some known bugs

**Comment by DerekJi2** [comment]
If there's anything wrong, just send me a screen shot so that I'm able to know what happened
--
Today I had a sick leave, so the progress is faster. Tomorrow it will not move as fast as today. :)

**Comment by Mouris1** [comment]
ok not a problem thanks

**Comment by DerekJi2** [comment]
Database Updated
--
1. Drop Database SpotterProp
2. Create Database SpotterProp
3. Execute the SQL below
[DB_SpotterProp.zip](https://github.com/Mouris1/SpotterProps/files/1580619/DB_SpotterProp.zip)

**Comment by Mouris1** [comment]
i can't access the myspotter.com
![123](https://user-images.githubusercontent.com/34412949/34380407-1fe84ff0-eb51-11e7-97a8-d4e5a061b46a.gif)

**Comment by DerekJi2** [comment]
Have you checked hosts file?
C:\Windows\System32\drivers\etc
