### ISSUE TITLE
Admin Portal - Tendoo-cms Test & Configurations

### ISSUE THREAD

**Issue by DerekJi2** [Mouris1/SpotterProps#10]
Work with Tendoo-cms and let it run! 

https://github.com/Blair2004/tendoo-cms

It is based on CodeIgniter framework, and only provides insfractures

**Comment by DerekJi2** [comment]
# Configurations
It provides online setup functions.

Nothing wrong happened when I was working on it.
![tendoocms](https://user-images.githubusercontent.com/29216624/34941017-dd1c4924-fa41-11e7-9757-2e7e70d0a029.gif)

**Comment by DerekJi2** [comment]
# Issue: "[] operator not supported for strings" in Notice.php
![image](https://user-images.githubusercontent.com/29216624/34941134-62a86bea-fa42-11e7-9518-98aaff616132.png)

## Root Cause
Exceptions were thrown out as trying to assign a string to array.
![image](https://user-images.githubusercontent.com/29216624/34941162-83dead4c-fa42-11e7-9dfb-e24052ae6413.png)

## Solution
Change as above

**Comment by DerekJi2** [comment]
# Issue: "[] operator not supported for strings" in Notice.php
![image](https://user-images.githubusercontent.com/29216624/34941134-62a86bea-fa42-11e7-9518-98aaff616132.png)

## Root Cause
Exceptions were thrown out as trying to assign a string to array.
![image](https://user-images.githubusercontent.com/29216624/34941162-83dead4c-fa42-11e7-9dfb-e24052ae6413.png)

## Solution
Change as above

**Comment by DerekJi2** [comment]
# Things to do with Tendoo-cms

## Step 1. Integrate Spotter database with Tendoo
Basically, Tendoo's database only includes tables for users/auth. So what we need to do is:
1. update database name & tables
2. update prefix for tables
3. integrate database to Tendoo's Do-setup process (currently, do it from back-end)
![image](https://user-images.githubusercontent.com/29216624/34941297-19690092-fa43-11e7-8076-4fb21f5d5443.png)

## Step 2. Provide operations for properties
Including Add/Update/Delete/Approve

## Step 3. Changes on Spotter 
List only approved properties from Tendoo. It includes some back-end changes, and front-end search functions.

## Step 4. Website planning & Test Deployment
Try to deploy 2 sites as below to know what kind of problems we may have and try to solve them.
Spotter -> www.syrianproperties.com
Tendoo -> admin.syrianproperties.com

## Step 5. Permission Controls
Tendoo is providing such functions. However, from the configured site, it seems that there're no online functions to configure all the permissions ...
Therefore, we have to:
1. Confirm Tendoo's permission control is working;
2. Config Tendoo's permission control as what we expect;
3. If possible, try to implement functions to provide online configurations

## Step 6. 'ONE FREE PROPERTY' functions

**Comment by BabaDBA** [comment]
Dashboard 
A PHP Error was encountered
Severity: Warning

Message: count(): Parameter must be an array or an object that implements Countable

Filename: libraries/Aauth.php

Line Number: 1894

Backtrace:

File: C:\xampp\htdocs\cms\application\libraries\Aauth.php
Line: 1894
Function: _error_handler

File: C:\xampp\htdocs\cms\application\mu-modules\aauth\inc\fields.php
Line: 310
Function: get_errors_array

File: C:\xampp\htdocs\cms\application\libraries\Events.php
Line: 392
Function: displays_dashboard_errors

File: C:\xampp\htdocs\cms\application\views\dashboard\gui\body.php
Line: 40
Function: do_action

File: C:\xampp\htdocs\cms\application\core\Tendoo_Loader.php
Line: 1090
Function: include

File: C:\xampp\htdocs\cms\application\core\Tendoo_Loader.php
Line: 593
Function: _ci_load

File: C:\xampp\htdocs\cms\application\models\Gui.php
Line: 240
Function: view

File: C:\xampp\htdocs\cms\application\views\dashboard\index\body.php
Line: 23
Function: output

File: C:\xampp\htdocs\cms\application\core\Tendoo_Loader.php
Line: 1090
Function: include

File: C:\xampp\htdocs\cms\application\core\Tendoo_Loader.php
Line: 593
Function: _ci_load

File: C:\xampp\htdocs\cms\application\models\Dashboard_Model.php
Line: 109
Function: view

File: C:\xampp\htdocs\cms\application\models\Gui.php
Line: 65
Function: index

File: C:\xampp\htdocs\cms\application\controllers\Dashboard.php
Line: 122
Function: load_page

File: C:\xampp\htdocs\cms\index.php
Line: 283

**Comment by BabaDBA** [comment]
how to fix above issue
