### ISSUE TITLE
February 4th - Meeting Minutes

### ISSUE THREAD

**Issue by DerekJi2** [Mouris1/SpotterProps#19]
# 1. Update **About** Page as dynamically
1) Show information dynamically
2) Able to edit info online
3) Support multi languages;
4) Only Admin can edit

# 2. Update **Contact** Page as dynamically
1) Show information dynamically
2) Able to edit info online
3) Support multi languages;
4) Only Admin can edit

# 3. Update favicon

# 4. Website meta keywords for SEO
1) able to edit online
2) only Admin can edit
3) load dynamically
4) support multi languages

# 5. Admin.Dashboard: list top 5 latest properties

# 6. Able to update "number per page" online for Spotter.Listing

# 7. Able to update "number per page" online for Admin.Property.List

# 8. Show user photo on right-top corner

# 9. Solve the problem of display_public_errors

# 10. Update all currency from $ to "SYP"

# 11. Able to online edit items defined in arabic(chinese)/home_lang.php

**Comment by Mouris1** [comment]
can you let me know how many hours it would take you to do this changes?
thanks.

**Comment by DerekJi2** [comment]
Estimations & Working Plan
--
[Estimations & Working Plan.xlsx](https://github.com/Mouris1/SpotterProps/files/1698670/Estimations.Working.Plan.xlsx)

![image](https://user-images.githubusercontent.com/29216624/35855175-6e0490ea-0b6d-11e8-88c7-d2fa61fec76c.png)

**Comment by DerekJi2** [comment]
No.1 - Update About Page as dynamically
--
![aboutus](https://user-images.githubusercontent.com/29216624/36056878-2c9a1fe8-0e43-11e8-821c-e046f37bfa2e.gif)

**Comment by DerekJi2** [comment]
No.2 - Update Contact Page as dynamically
--
![contact](https://user-images.githubusercontent.com/29216624/36056930-a89062a6-0e43-11e8-94bc-d921aec74efb.gif)

**Comment by DerekJi2** [comment]
No.3 - Update favicon
--
![favicon](https://user-images.githubusercontent.com/29216624/36056987-4be6f582-0e44-11e8-8851-a181431fff27.gif)

**Comment by DerekJi2** [comment]
No.5 - Admin.Dashboard: list top 5 latest properties
--
1. Show up to 5 latest properties;
2. for users, only show their own properties
3. for editor/admin, show all properties (maximum 5)
![dashboard-latest5](https://user-images.githubusercontent.com/29216624/36061876-1d8c1f34-0e9c-11e8-9940-e3b04f9d7f49.gif)

**Comment by DerekJi2** [comment]
No.8 - Show user photo on right-top corner
--
![user-photo](https://user-images.githubusercontent.com/29216624/36067456-a097ef6e-0ef8-11e8-82a6-0438a1c0b270.gif)

**Comment by DerekJi2** [comment]
No. 4 - Website meta keywords for SEO
--
1. able to edit online
2. only Admin can edit
3. load dynamically
4. support multi languages
![seo](https://user-images.githubusercontent.com/29216624/36199339-3cc62762-11b4-11e8-976a-7d79b7aa1118.gif)

**Comment by DerekJi2** [comment]
No. 6 - Able to update "number per page" online for Spotter.Listing
No. 7 - Able to update "number per page" online for Admin.Property.List
--
![number-per-page](https://user-images.githubusercontent.com/29216624/36199600-f8b46e2a-11b4-11e8-8498-f89655987916.gif)

**Comment by DerekJi2** [comment]
No.10 - Update all currency from $ to "SYP"
--
![syp](https://user-images.githubusercontent.com/29216624/36199736-6c171a84-11b5-11e8-8a4a-edb50173f5d5.gif)

**Comment by DerekJi2** [comment]
No.11 - Able to online edit items defined in arabic(chinese)/home_lang.php
--
![multi-lang](https://user-images.githubusercontent.com/29216624/36305882-74918216-1350-11e8-9760-f32254dbc6d8.gif)

**Comment by DerekJi2** [comment]
No.12 - Notifications to users
--
![notification](https://user-images.githubusercontent.com/29216624/36348444-b3afeb58-14aa-11e8-8ee7-ab9d3c58b8f5.gif)

**Comment by DerekJi2** [comment]
All tasks completed
--
![image](https://user-images.githubusercontent.com/29216624/36348559-277f90cc-14ad-11e8-8885-fcdddf67ac17.png)
