### ISSUE TITLE
HomePage - Search Functions

### ISSUE THREAD

**Issue by DerekJi2** [Mouris1/SpotterProps#2]
On the main page, implement search functions including

**1. Load the property types dynamically;**
--
![image](https://user-images.githubusercontent.com/29216624/34326536-e1948b64-e8fe-11e7-8ea4-8907ecb74f0a.png)

**2. Load the property features dynamically;**
--
![image](https://user-images.githubusercontent.com/29216624/34326544-0dbb90c0-e8ff-11e7-8810-b87cd382ccc0.png)

**3. Enable the plus/minus buttons**
--
![image](https://user-images.githubusercontent.com/29216624/34326548-1dcb2264-e8ff-11e7-85a8-9eddbbe12ce2.png)

**4. Load results dynamically based on search criteria**
--
![image](https://user-images.githubusercontent.com/29216624/34326551-69d0b3ae-e8ff-11e7-8b68-84474364f17a.png)

**Comment by DerekJi2** [comment]
Database Updated
--
1. Drop Database SpotterProp
2. Create Database SpotterProp
3. Execute the SQL below:
![image](https://user-images.githubusercontent.com/29216624/34398214-021d75d2-ebcd-11e7-8786-4dffb05ecfc7.png)
[DB_SpotterProp.zip](https://github.com/Mouris1/SpotterProps/files/1590253/DB_SpotterProp.zip)

**Comment by DerekJi2** [comment]
Completed & Demo
--
![mouris- 2-search](https://user-images.githubusercontent.com/29216624/34398072-717bf928-ebcb-11e7-8703-d91d978efdb5.gif)

**Comment by Mouris1** [comment]
good got that

**Comment by Mouris1** [comment]
looking better
